### ISSUE TITLE
invalid memory address or nil pointer dereference error will happen in Put method

### ISSUE THREAD

**Issue by barnettZQG** [valyala/bytebufferpool#12]
```
func (p *Pool) Put(b *ByteBuffer) {
    idx := index(len(b.B))

    if atomic.AddUint64(&p.calls[idx], 1) > calibrateCallsThreshold {
        p.calibrate()
    }

    maxSize := int(atomic.LoadUint64(&p.maxSize))
    if maxSize == 0 || cap(b.B) <= maxSize {
        b.Reset()
        p.pool.Put(b)
    }
}
```

if b is nil,len(b.B) will have a error.

```
if b==nil{
return
}
```

**Comment by valyala** [comment]
This is an expected behaviour - [Pool.Put](https://godoc.org/github.com/valyala/bytebufferpool#Pool.Put) accepts only valid pointers to [ByteBuffer](https://godoc.org/github.com/valyala/bytebufferpool#ByteBuffer). It doesn't accept nil pointers.

The [related issue in fasthttp](https://github.com/valyala/fasthttp/issues/193) has been fixed separately.
