### ISSUE TITLE
[Question] Why do you use self-made byte buffers?

### ISSUE THREAD

**Issue by bogem** [valyala/bytebufferpool#5]
Hi valyala! Thanks for your library. It reduced memory usage of my package by ~10%. 
But I have one question: why do you wrote your own self-made byte buffers and don't use buffers from standard bytes package? Buffers from bytes package have functions that I need (for example, ReadFrom), but your buffers haven't :(

**Comment by valyala** [comment]
Both [fasthttp](https://github.com/valyala/fasthttp) and [quicktemplate](https://github.com/valyala/quicktemplate) had almost identical `ByteBuffer` implementations, so I just extracted them into `bytebufferpool` package :)

`fasthttp` and `quicktemplate` don't use `bytes.Buffer`, because they need only a small subset of the functionality provided by `bytes.Buffer`. And this functionality should be tuned for performance.

**Comment by valyala** [comment]
@bogem , now `ByteBuffer` from `bytebufferpool` supports [ReadFrom](https://godoc.org/github.com/valyala/bytebufferpool#ByteBuffer.ReadFrom).

**Comment by bogem** [comment]
@valyala Thanks a lot!
